### ISSUE TITLE
Serve il while?

### ISSUE THREAD

**Issue by Pipeman** [thisthat/DMS-Project#5]
Nella funzione slideDown in index.html serve controllare che tutti i frame siano presenti in cache con un while? Non basterebbe salvarsi il numero di volte che è stato lanciato l'evento pageComplete, poi quando uno clicka pageDown si controlla se la nuova pagina è minore o uguale al numero di pagine completate.

**Comment by thisthat** [comment]
Si perché il pageComplete è lanciato a fine della pagina, mentre l'inserimento del singolo frame non è esportato come evento (che non avrebbe nemmeno senso) 
Per cui dobbiamo usare un while per vedere a che punto della pagina siamo arrivati.
Inoltre, anche se avessimo il numero esatto di frame inseriti, il numero di confronti sarebbe uguale!
